BidirectionalGraph as subclass of DirectedAdjacencyGraph
monora/rgl pull request #76
Opened 2023-02-13 18:42 UTC by jsjuni

2023-02-14 11:09 UTC, monora requested changes

2023-02-14 11:09 UTC, monora commented on test/bidirectional_graph_test.rb
> +class TestBidirectionalGraph < Test::Unit::TestCase
We could in addition reuse `TestDirectedGraph` here only overriding setup method:

```suggestion
class TestDirectedGraphBidirected < TestDirectedGraph
  def setup
    @dg = BidirectionalAdjacencyGraph.new
    # TODO: refactor this in a protected setup function which we reuse here
    [[1, 2], [2, 3], [3, 2], [2, 4]].each do |(src, target)|
      @dg.add_edge(src, target)
    end
  end
end
```

All tests in the super test class should then pass.

2023-02-14 13:40 UTC, jsjuni commented on lib/rgl/bidirectional.rb
> +    IN  = 1
That's essentially the first implementation I did. It was less intrusive than this one but also less efficient: The keys in the two vertex dicts are duplicated and all add/delete operations on vertices are duplicated. I'll make a PR for that version for comparison. It sounds closer to what you want.

2023-02-16 17:45 UTC, jsjuni commented on lib/rgl/bidirectional.rb
> -  module BidirectionalGraph
OK.

2023-02-21 16:11 UTC, monora commented
Close and release in #83

2023-02-21 16:11 UTC, closed without merging